replicaCount: 1

image:
  repository: woistes
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: ""

sqlserver:
  password: Woistes_Prod_Change_Me!
  storage: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
