<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Woistes.Domain\Woistes.Domain.csproj" />
    <ProjectReference Include="..\Woistes.Infrastructure\Woistes.Infrastructure.csproj" />
    <ProjectReference Include="..\Woistes.CtfParser\Woistes.CtfParser.csproj" />
  </ItemGroup>

</Project>
