apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  sa-password: {{ .Values.sqlserver.password }}
  connection-string: "Server={{ .Chart.Name }}-sqlserver;Database=Woistes;User Id=sa;Password={{ .Values.sqlserver.password }};TrustServerCertificate=True"
  google-client-id: {{ .Values.auth.googleClientId | quote }}
  google-client-secret: {{ .Values.auth.googleClientSecret | quote }}
  allowed-emails: {{ .Values.auth.allowedEmails | join "," | quote }}
