apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sqlserver
spec:
  serviceName: {{ .Chart.Name }}-sqlserver
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-sqlserver
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: sa-password
          volumeMounts:
            - name: sqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: sqldata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.sqlserver.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-sqlserver
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: {{ .Chart.Name }}-sqlserver
